### ISSUE TITLE
T側での録画ができない

### ISSUE THREAD

**Issue by kazuki0824** [nns779/px4_drv#1]
dvr1@DVR1:~/px4_drv/driver$ recpt1 --device /dev/px4video2 13 10 test.ts
using device: /dev/px4video2
Cannot open tuner device: /dev/px4video2

CPUはAMD A10-9700E
OSは Ubuntu 17.10.1で、カーネルのバージョンは以下のとおりです
dvr1@DVR1:~/px4_drv/driver$ uname -a
Linux DVR1 4.15.5-041505-generic #201802221031 SMP Thu Feb 22 15:32:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lsしてもやはりデバイスファイルは作成されていることが確認できるのですが、いざ録画しようと思うと、デバイスが開けません。

**Comment by kazuki0824** [comment]
書き忘れていたので追記します。
使用したデバイスはPX-W3PE4です。

**Comment by nns779** [comment]
T側(px4video2,3)はチューナーIC(Rafael Micro R850)のドライバが現在実装できていないため使用できません。デバイスファイルを開こうとするとcdevドライバ側でエラーを返すようになっています。
そのため、現在使用できるのはS側(px4video0,1)のみとなっています。紛らわしくてすみません。

**Comment by kazuki0824** [comment]
デバイスを持っているので、可能ならば私のほうでもそこの実装を試みたいです。
調べた限りではデータシートの類はないようですね。何か参考になる情報はお持ちでしょうか。

**Comment by nns779** [comment]
現状では公式ドライバを逆アセンブルした結果とデバッグ情報、ICチップの機能が似ていると思われるR848というチューナーのドライバのソースコードしか参考になるものがないように思います。

デバッグ情報ですが、公式ドライバのソースコード上の変数名や型情報などが残っています。(残っているのは一部のバージョンの公式Linuxドライバに限るようですが…)

そしてR848というチューナーですが、R850との差異が不明なため、ドライバのソースコードが実際に参考になるかならないかは分かりません。R848のドライバのソースコードはWebで検索するとヒットします。

いずれにせよ、まとまった資料は存在しないのが現状です。

**Comment by nns779** [comment]
長らくお待たせいたしました。
0a43c3b にてUHFの13-52ch限定ですがT側(px4video2,3)での録画ができるようになりました。
ご確認いただければ幸いです。

**Comment by nns779** [comment]
0169833 にてCATV C13-C63chの定義を追加いたしました。

**Comment by nns779** [comment]
特に問題なさそうですので閉じます。
