### ISSUE TITLE
PX-MLT5PE

### ISSUE THREAD

**Issue by xswqaz** [nns779/px4_drv#5]
PX-MLT5PEは対応しているのでしょうか。

**Comment by nns779** [comment]
px4_drvはPX-MLT5PEには対応しておりません。
しかし、今後PX-MLT5PEのUSB外付け版が発売され、それがWindowsでまともに動作するようでしたら、新たにLinuxドライバを作成しようかとは考えています。
ですが、必ずドライバを作成するというお約束は致しかねますので、その点はあらかじめご了承ください。

**Comment by xswqaz** [comment]
承知しました。ありがとうございます。
