### ISSUE TITLE
DTV02-1T-Uへ対応できるか

### ISSUE THREAD

**Issue by basashi-G** [nns779/px4_drv#8]
e-better製のDTV02-1T1S-Uに試験的に対応しているそうですが、カードリーダが付属していない下位機種と思われる[DTV02-1T-U](https://www.e-better.jp/?pid=130718943)にも使えますか？実際に試したところ、カーネルモジュールはロードされているのですが、usbデバイスを接続しても/devディレクトリに新たなデバイスファイルがされません。px4_drvを` lsmod`で確認したところ、適用されている形跡がありません。USBデバイスに適用させるドライバを指定することはできますか？

**Comment by nns779** [comment]
申し訳ないのですが、px4_drvでDTV02-1T-Uを使用することはできません。

DTV02-1T-Uは、DTV02-1T1S-UのようなTSデータへの復調処理をハードウェア側で行う一般的なPC向けデジタル放送用のチューナーとは異なり、ハードウェアでは放送波をI/Q信号に変換したものをデジタル化してPCに送信し、TSデータへの復調処理はPC上のソフトウェアで行うSDRタイプのチューナーとなっています。
そのため、DTV02-1T-UをLinuxで使用するためには、SDRチューナーとしてI/Q信号をやり取りするドライバと、I/Q信号からISDB-TのTSデータの復調処理を行うソフトウェアが必要となります。

これらはpx4_drvで扱うことができるようなものではないので、対応の予定もありません。

ご了承ください。
